spring:
  datasource:
    url: jdbc:sqlserver://irfan-cricketplayer.database.windows.net:1433;database=dbo;user=root123;password={Password@213};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect



